### ISSUE TITLE
[Q/Feat Req] Proper shutdown of the server

### ISSUE THREAD

**Issue by ghost** [TheRemote/Legendary-Minecraft-Purpur-Geyser#3]
Hey once again 😄 

As far as I know, the current docker way to shut things down, is to send a `SIGTERM` signal.

But this doesn't shut down the server properly. At least not in my experience. It doesn't trigger the right shutdown procedure, including the `save-all`, that a normal/proper server shutdown would.

What I do at the moment, to do a proper shutdown, is `docker attach mcs01` and then a CTRL-C in the screen attached, and afterwards I run a `docker stop mcs01`, to make the container itself shut down properly.

I'm not *too* knowledgable with docker, but would it be possible to trigger a proper shutdown script or something, before sending the `SIGTERM` signal?

That would be awesome :) so that when you run the `docker stop mcs01`, it would trigger the proper shutdown of the `screen` running the server, and then a SIGTERM for the container itself.

**Comment by TheRemote** [comment]
Hello again!  I definitely am following what you're saying.  I did some research and was able to find this:

https://madflojo.medium.com/shutdown-signals-with-docker-entry-point-scripts-5e560f4e2d45

It looks like this is actually a really common mistake with entrypoints and that it's actually really easy to fix.  If I simply add "exec" in front of the launch lines for screen (or java if running without screen) then it will completely replace the running context and will actually catch SIGTERM commands.

This should fix it because screen does pass sigterm commands and shut down the server.  The problem is with Docker entrypoints and it looks like the fix is quite easy.  I'll get this added in here today!

**Comment by ghost** [comment]
> Hello again! I definitely am following what you're saying. I did some research and was able to find this:
> 
> https://madflojo.medium.com/shutdown-signals-with-docker-entry-point-scripts-5e560f4e2d45
> 
> It looks like this is actually a really common mistake with entrypoints and that it's actually really easy to fix. If I simply add "exec" in front of the launch lines for screen (or java if running without screen) then it will completely replace the running context and will actually catch SIGTERM commands.
> 
> This should fix it because screen does pass sigterm commands and shut down the server. The problem is with Docker entrypoints and it looks like the fix is quite easy. I'll get this added in here today!

You're a legend mate, thanks for the quick reply :)

**Comment by TheRemote** [comment]
This should be ready to test now with a:

`docker pull 05jchambers/legendary-minecraft-purpur-geyser`

Everything seems to be appearing to work correctly for me here but let's have you check and confirm!

**Comment by ghost** [comment]
Doesn't seem to work here :/
I'm using the screen option, if that matters.

Here's an example of what happens:
https://i.imgur.com/AjGzZGK.gif

In console window 1 in run the `docker stop mcs01` command. In the other console window, I have the `docker attach mcs01` running. It doesn't seem to shut down in the proper way :(.

Not sure if it's caused by the `screen`??

**Comment by ghost** [comment]
Ah, it seems to the work without the `screen` option.

So setting the variable, `NoScreen=Y` it totally works:
https://i.imgur.com/SHzcDgn.gif

That's enough for me lol 👍 . I'm closing this issue for now

**Comment by TheRemote** [comment]
Hey vp-en,

No worries at all, thanks for testing it!  The screen application is mostly an artifact from the standalone version and doesn't make a lot of sense for this version.  The only reason it was used was for logging but Docker keeps it's own instance logs anyways so these are already available and it's just duplicated functionality (that apparently is making it not work as well).

The latest version has screen removed altogether!
