### ISSUE TITLE
Startup script options

### ISSUE THREAD

**Issue by BinaryConstruct** [TheRemote/Legendary-Minecraft-Purpur-Geyser#5]
Would it be possible to add flags to the startup script to disable certain features such as `fixpermissions.sh` and the backup section?

My server has a large number of files, and these two items take a significant amount of time during a server reboot, and `fixpermissions` isn't really needed every restart. 

Another issue is if you are using the https://www.spigotmc.org/resources/server-backup-world-ftp-backup-1-8-1-19-multithreaded.79320/ plugin, it creates a `Backups`  (note casing) folder that can really inflate the size of the startup backups. It would be nice to exclude this folder as well.

Thanks for this awesome project! I'm a big fan of your blog posts as well.
![image](https://user-images.githubusercontent.com/456755/197044604-81c8bac3-2bbc-4d00-a443-bb41785fc0da.png)

**Comment by TheRemote** [comment]
Hey BinaryConstruct,

Welcome!  I think I can absolutely add both of these things.  I totally understand where you're coming from on both counts.  

Thanks a ton for sponsoring the project as well, that's a huge deal right now as I'm trying to figure out how to keep doing what I'm doing in this economy.  GitHub doubles everyone's sponsorship contributions too so I can't thank you enough!  I'm glad you enjoy the blog as well!

I should be able to get these in by this weekend I'd imagine.  I'll definitely post an update here as progress continues as well!

**Comment by TheRemote** [comment]
This is ready for testing.  Just do a:

`docker pull 05jchambers/legendary-minecraft-purpur-geyser:latest`

"NoBackup" - Skip backing up a certain folder-- for example if you wanted to skip the plugins/ftp folder you would do 
`-e NoBackup="plugins/ftp"`
"NoPermCheck" - Skips the permission check with -e NoPermCheck="Y"
"ScheduleRestart" -- this schedules the container to shut down at a certain time which combined with the --restart switch gives daily reboot functionality.  Use 24 hour time such as 03:30 for 3:30am.  This one was for someone else but I'm going to release it with the same update.

Can you give these a try at your earliest convenience and see if they are working properly for you?

**Comment by BinaryConstruct** [comment]
Great! I just tested all of these and they are working as intended. The only thing that might be nice is if the `NoBackup` allowed  multiple folder lists e.g. `Backups,plugins/dynmap/web/tiles,plugins/ftp`.

**Comment by BinaryConstruct** [comment]
Something like this (note, this is untested and I just wrote in the github inline window, so it probably has malformed syntax).

```sh
       
            tarArgs=(-I pigz --exclude='./backups' --exclude='./cache' --exclude='./logs' --exclude='./jre' --exclude='./purpur.jar')
            for p in "${NoBackup[@]}" ; do 
                tarArgs+=(--exclude="./$p")
            done
            tarArgs+=(-pvcf backups/$(date +%Y.%m.%d.%H.%M.%S).tar.gz ./*)
            tar "${tarArgs[@]}"

```
