### ISSUE TITLE
administration help

### ISSUE THREAD

**Issue by murugaratham** [TheRemote/Legendary-Minecraft-Purpur-Geyser#8]
i'm new to hosting a minecraft server, i'm just trying it out for family, in the readme:

```
If you are using Docker Desktop on Mac then you need to access the Docker VM with the following command first:
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
```

I'm guessing that's for intel macs, i'm on M1, but that aside, how do i write admin command for the server? I'm ran `docker exec -it <container_id>` but no clue where and how to run minecraft commands, e.g. tp some players, is there any page that gives a list of command where u can point me to?

**Comment by TheRemote** [comment]
Hello,

There's not going to be any consistent paths for Mac.  To find the path on that platform you'll probably need to do:

`docker volume inspect yourvolumename`

This will give you the full path to the files under "Mountpoint".

For the admin commands I would recommend just typing:

`op yourplayername`

in the console.  Don't use a forward slash in the console.  After that you can use commands in-game.

A list of commands is here:  https://minecraft.fandom.com/wiki/Commands

Hopefully that helps!

**Comment by murugaratham** [comment]
Thanks for the quick response & tips, I saw rcon and it seems like it might make it easier to manage, but thanks for explaining
